#########################################################################
#									#
# Author: Copyright (C) 2023  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# Configuration file for GitHub dependabot checks and updates.          #
#									#
#########################################################################


version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


