#########################################################################
#									#
# File ID: ./.github/dependabot.yml                                     #
# Author: Copyright (C) 2023  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
# Configuration file for GitHub dependabot checks and updates.          #
#									#
#########################################################################

#########################################################################
#									#
# Changelog								#
#									#
# Date		Author	Version	Description				#
#									#
# 06/09/2023	MG	1.0.1	Initial release.                        #
#									#
#########################################################################


version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


