#########################################################################
#									#
# Author: Copyright (C) 2026  Mark Grant				#
#									#
# Released under the GPLv3 only.					#
# SPDX-License-Identifier: GPL-3.0-only					#
#									#
# Purpose:								#
#	AutoMake script file to run tests under make check.		#
#									#
#########################################################################


TESTS = ../tests/shellcheck/run-dot-sh-dot-in-pattern.sh
TESTS += ../tests/shellcheck/shellcheck-inline-dot-sh.sh

